#!/usr/bin/env python3
"""Regenerate wiki/index.md from the frontmatter of every wiki page.

index.md is a DERIVED artifact — never hand-edit it. Edit pages, then run:

    python3 scripts/build_index.py

Because the index is generated (not hand-merged), parallel worktree sessions
never touch it and so never conflict on it. The companion rule
`wiki/log.md merge=union` (see .gitattributes) lets the append-only log merge
cleanly too. Together they make worktree-isolated sessions safe for this wiki.

Usage:
    python3 scripts/build_index.py            # regenerate wiki/index.md
    python3 scripts/build_index.py --check     # report drift, write nothing (exit 1 if stale)
    python3 scripts/build_index.py --wiki DIR  # operate on a different wiki root
"""
from __future__ import annotations

import argparse
import datetime
import sys
from pathlib import Path

# Core categories in display order: (dirname, heading, italic description).
CATEGORIES = [
    ("entities", "Entities", "People, organizations, products, places, datasets, tools."),
    ("concepts", "Concepts", "Ideas, methods, definitions, claims, mental models."),
    ("sources", "Sources", "One page per ingested `raw/` source."),
]
SPECIAL = {"index.md", "log.md"}
# Marker line that carries the regeneration timestamp; ignored by --check.
STAMP_PREFIX = "> _Generated by `scripts/build_index.py`"


def parse_frontmatter(text: str) -> tuple[dict[str, str], str]:
    """Return (meta, body). Tolerates pages with no frontmatter."""
    meta: dict[str, str] = {}
    if not text.startswith("---"):
        return meta, text
    end = text.find("\n---", 3)
    if end == -1:
        return meta, text
    block = text[3:end].strip("\n")
    body = text[end + 4:]
    for line in block.splitlines():
        line = line.rstrip()
        if not line or line.lstrip().startswith("#") or ":" not in line:
            continue
        key, _, val = line.partition(":")
        meta[key.strip()] = val.strip()
    return meta, body


def one_line_definition(body: str, limit: int = 180) -> str:
    """The page's opening definition: the first paragraph, whitespace-collapsed.

    Pages hard-wrap the definition sentence across physical lines, so accumulate the
    whole first paragraph (consecutive non-empty, non-heading lines) rather than a single
    line, then truncate to keep the index entry to one row.
    """
    para: list[str] = []
    for line in body.splitlines():
        s = line.strip()
        if not para:
            if not s or s.startswith("#"):
                continue          # skip blanks and the H1 before the definition
            para.append(s)
        elif s and not s.startswith("#"):
            para.append(s)        # continuation of the same paragraph
        else:
            break                 # blank line or heading ends the paragraph
    text = " ".join(para)
    return text if len(text) <= limit else text[: limit - 1].rstrip() + "…"


def collect(cat_dir: Path) -> list[dict[str, str]]:
    rows: list[dict[str, str]] = []
    if not cat_dir.is_dir():
        return rows
    for p in sorted(cat_dir.glob("*.md")):
        if p.name in SPECIAL:
            continue
        meta, body = parse_frontmatter(p.read_text(encoding="utf-8"))
        missing = [f for f in ("title", "updated", "status") if not meta.get(f)]
        if missing:
            print(f"warn: {p.relative_to(cat_dir.parent)} missing {', '.join(missing)}",
                  file=sys.stderr)
        rows.append({
            "name": p.stem,
            "title": meta.get("title") or p.stem,
            "summary": one_line_definition(body),
            "updated": meta.get("updated", "?"),
            "status": meta.get("status", "?"),
        })
    rows.sort(key=lambda r: r["title"].lower())
    return rows


def sections(wiki: Path) -> list[tuple[str, str, list[dict[str, str]]]]:
    out: list[tuple[str, str, list[dict[str, str]]]] = []
    known = {d for d, _, _ in CATEGORIES}
    for dirname, heading, desc in CATEGORIES:
        out.append((heading, desc, collect(wiki / dirname)))
    # Auto-discover any extra category folders (e.g. events/, decisions/).
    for d in sorted(p for p in wiki.iterdir() if p.is_dir()):
        if d.name not in known:
            rows = collect(d)
            if rows:
                out.append((d.name.capitalize(), "", rows))
    return out


def render(secs: list[tuple[str, str, list[dict[str, str]]]], stamp: str) -> str:
    total = sum(len(rows) for _, _, rows in secs)
    lines = [
        "# Wiki Index",
        "",
        "The catalog of every page in this wiki, grouped by category. Read this first when",
        "answering a query.",
        "",
        f"{STAMP_PREFIX} on {stamp} — do not hand-edit; edit pages, then regenerate._",
        "> Format per entry: `- [[page-name]] — one-line summary _(updated: YYYY-MM-DD · status)_`",
        "",
        f"**{total} page{'s' if total != 1 else ''}** across the categories below.",
        "",
    ]
    for heading, desc, rows in secs:
        lines.append(f"## {heading}")
        if desc:
            lines.append(f"_{desc}_")
        lines.append("")
        if rows:
            for r in rows:
                lines.append(
                    f"- [[{r['name']}]] — {r['summary']} "
                    f"_(updated: {r['updated']} · {r['status']})_"
                )
        else:
            lines.append("_(none yet)_")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def strip_stamp(text: str) -> str:
    """Drop the timestamp line so --check ignores time-only changes."""
    return "\n".join(l for l in text.splitlines() if not l.startswith(STAMP_PREFIX))


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description="Regenerate wiki/index.md from page frontmatter.")
    ap.add_argument("--wiki", type=Path, default=Path(__file__).resolve().parent.parent / "wiki")
    ap.add_argument("--check", action="store_true",
                    help="report drift and exit 1 if stale; write nothing")
    args = ap.parse_args(argv)

    wiki: Path = args.wiki
    if not wiki.is_dir():
        print(f"error: wiki dir not found: {wiki}", file=sys.stderr)
        return 2

    now = datetime.datetime.now().astimezone()
    stamp = now.strftime("%Y-%m-%d %H:%M %Z").strip()
    secs = sections(wiki)
    new = render(secs, stamp)
    index_path = wiki / "index.md"

    if args.check:
        old = index_path.read_text(encoding="utf-8") if index_path.exists() else ""
        if strip_stamp(old) == strip_stamp(new):
            print("index.md is up to date.")
            return 0
        print("index.md is STALE — run scripts/build_index.py to regenerate.", file=sys.stderr)
        return 1

    index_path.write_text(new, encoding="utf-8")
    total = sum(len(rows) for _, _, rows in secs)
    print(f"Wrote {index_path} — {total} pages, generated {stamp}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
